name: Get Latest Version
on:
  workflow_call:
    outputs:
      formatted_version:
        description: "Formatted version string"
        value: ${{ jobs.get_latest_version.steps.findandreplace.outputs.value }}

jobs:
  get_latest_version:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "test"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: 'Find and remove v from version'
        uses: mad9000/actions-find-and-replace-string@2
        id: findandreplace
        with:
          source: ${{ steps.previoustag.outputs.tag }}
          find: 'v'
          replace: ''
