on:
  push:
    branches:
      - main


jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Echo Labels
          run: echo ${{ github.event.label }}
          
        - name: Run workflow for a major release
          if: ${{ github.event.label.name == 'major' }}
          run: echo 'Running workflow for a major release...'
          
        - name: Run workflow for a minor release
          if: ${{ github.event.label.name == 'minor' }}
          run: echo 'Running workflow for a minor release...'
          
        - name: Run workflow for a patch release
          if: ${{ github.event.label.name == 'patch' }}
          run: echo 'Running workflow for a patch release...'

