on:
  push:
    branches:
      - main


jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Run workflow for a minor release
          if: ${{ github.event.label.name == 'minor' }}
          run: echo 'Running workflow for a minor release...'

        - name: Do NOT run workflow for a minor release
          if: ${{ !github.event.label.name == 'minor' }}
          run: echo 'NOT running workflow for a minor release...'

