name: Release Branch Versioning
on:
  workflow_dispatch:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main


jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.patch }}

      - name: Run workflow for a major release
        if: contains( github.event.pull_request.labels.*.name, 'major')
        run: echo 'Running workflow for a major release...'

      - name: Run workflow for a minor release
        if: contains( github.event.pull_request.labels.*.name, 'minor')
        run: echo 'Running workflow for a minor release...'

      - name: Run workflow for a patch release
        if: contains( github.event.pull_request.labels.*.name, 'patch')
        run: echo 'Running workflow for a patch release...'
