on:
  pull_request:
    types:
      - labeled
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest
      if: ${{ github.event.label.name == 'minor' }}
      steps:
        - name: Run workflow for a minor release
          run: echo 'Running workflow for a minor release...'
#   createrelease:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

#       - name: 'Get Previous tag'
#         id: previoustag
#         uses: "WyriHaximus/github-action-get-previous-tag@v1"



#       - name: Bump release version
#         id: bump_version
#         uses: christian-draeger/increment-semantic-version@1.0.3
#         with:
#           current-version: ${{ steps.previoustag.outputs.tag }}
#           version-fragment: 'feature'

#       - name: Do something with your bumped release version
#         run: echo ${{ steps.bump_version.outputs.next-version }}

