name: Release Branch Versioning
on:
#   workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main


jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
# Get latest release version
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          
# =======================================================================================
# Remove "v" from version string
      - name: 'Find and remove v from version'
        uses: mad9000/actions-find-and-replace-string@2
        id: findandreplace
        with:
          source: ${{ steps.previoustag.outputs.tag }}
          find: 'v'
          replace: ''
          
# =======================================================================================
# If patch release
      - name: Bump release version
        if: contains( github.event.pull_request.labels.*.name, 'patch')
        id: bump_version_patch
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: ${{ steps.findandreplace.outputs.value }}
          version-fragment: 'bug'

# If minor release
      - name: Bump release version
        if: contains( github.event.pull_request.labels.*.name, 'minor')
        id: bump_version_minor
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: ${{ steps.findandreplace.outputs.value }}
          version-fragment: 'feature'

# If major release
      - name: Bump release version
        if: contains( github.event.pull_request.labels.*.name, 'major')
        id: bump_version_major
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: ${{ steps.findandreplace.outputs.value }}
          version-fragment: 'major'
          
# =======================================================================================
# Do something with output
      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version_patch.outputs.next-version }}
